const CUSTOMERS_BASE = "/customers";
const CUSTOMER_AUTH_BASE = "/customer-auth";

export const API_ROUTES = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    clearSessions: "/auth/clear-sessions",
  },
  users: {
    me: "/users/me",
    changePassword: "/users/me/password",
    register: "/users/register",
    list: "/users",
    create: "/users",
    find: "/users/find",
    update: "/users",
    delete: "/users",
  },
  audit: {
    list: "/audit",
  },
  products: {
    list: "/products",
    create: "/products",
    find: "/products/find",
    update: "/products",
    delete: "/products",
    restore: "/products/restore",
    photo: "/products/photo",
    photoUploadUrl: "/products/photo/upload-url",
  },
  stockEntries: {
    list: "/stock-entries",
    create: "/stock-entries",
    find: "/stock-entries/find",
    reverse: "/stock-entries/reverse",
  },
  sales: {
    list: "/sales",
    create: "/sales",
    find: "/sales/find",
    cancel: "/sales/cancel",
  },

  customers: {
    list: CUSTOMERS_BASE,
    create: CUSTOMERS_BASE,
    find: `${CUSTOMERS_BASE}/find`,
    update: CUSTOMERS_BASE,
    delete: CUSTOMERS_BASE,
    export: `${CUSTOMERS_BASE}/export`,
    purchases: (id: string) => `${CUSTOMERS_BASE}/${id}/purchases`,
    rankingByAmount: `${CUSTOMERS_BASE}/ranking/by-amount`,
    rankingByPurchases: `${CUSTOMERS_BASE}/ranking/by-purchases`,
  },
  alerts: {
    list: "/alerts",
    count: "/alerts/count",
    resolve: (id: string) => `/alerts/${id}/resolve`,
  },
  dashboard: {
    summary: "/dashboard/summary",
    topProducts: "/dashboard/top-products",
    topClubs: "/dashboard/top-clubs",
    sizes: "/dashboard/sizes",
    channels: "/dashboard/channels",
    margins: "/dashboard/margins",
    idleProducts: "/dashboard/idle-products",
    paymentMethods: "/dashboard/payment-methods",
    stockVelocity: "/dashboard/stock-velocity",
    reorderList: "/dashboard/reorder-list",
    capitalByClub: "/dashboard/capital-by-club",
    clubTrend: "/dashboard/club-trend",
    customersByTeam: "/dashboard/customers-by-team",
    reservationConversion: "/dashboard/reservation-conversion",
  },
  customerAuth: {
    magicLink: `${CUSTOMER_AUTH_BASE}/magic-link`,
    verify: `${CUSTOMER_AUTH_BASE}/verify`,
    logout: `${CUSTOMER_AUTH_BASE}/logout`,
    orders: `${CUSTOMER_AUTH_BASE}/me/orders`,
  },
} as const;
